/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#297AD6',
        'primary-dark': '#2162AB',
        'primary-alt': '#3880FF',
        'primary-subtle': '#EAF2FB',
        orange: '#E06714',
        'orange-light': '#EE781D',
        yellow: '#F9AE2B',
        teal: '#3086A3',
        success: '#027A48',
        error: '#EF0A0A',
        warning: '#F9AE2B',
        bg: '#F7F9FC',
        surface: '#FFFFFF',
        'surface-alt': '#F7F9FC',
        border: '#EAEAEB',
        'border-light': '#F5F5F5',
        'border-focus': '#297AD6',
        'text-primary': '#1F242A',
        'text-body': '#2B323B',
        'text-secondary': '#555B62',
        'text-tertiary': '#71767C',
        'text-muted': '#BDC0C2',
        'text-indigo': '#3D3D5A',
        'text-inverse': '#FFFFFF',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        roboto: ['Roboto', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        sm: '4px',
        md: '6px',
        card: '12px',
        hero: '16px',
        pill: '100px',
        input: '8px',
      },
    },
  },
  plugins: [],
};
