name: CICD

on:
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            github/data/general/docker/esatya username | DOCKERHUB_USERNAME ;
            github/data/general/docker/esatya password | DOCKERHUB_TOKEN ;
            github/data/rahat/rahat-impact-vendor-app env | ENV_SECRETS

      - name: Create .env file and export vars
        run: |
          echo "${{ env.ENV_SECRETS }}" > .env
          # Export each var to GitHub Actions env
          while IFS= read -r line; do
            [[ -z "$line" || "$line" == \#* ]] && continue
            echo "$line" >> $GITHUB_ENV
          done < .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            esatya/rahat-impact-vendor-app:dev
            esatya/rahat-impact-vendor-app:${{ github.sha }}
          build-args: |
            EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=${{ env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID }}
            EXPO_PUBLIC_API_URL=${{ env.EXPO_PUBLIC_API_URL }}
            EXPO_PUBLIC_CORE_API_URL=${{ env.EXPO_PUBLIC_CORE_API_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
